pipeline {

    agent any

    stages {

        stage('Terraform init') {

            steps {
                dir("cloud/terraform") {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform plan') {

            steps {
                dir("cloud/terraform") {
                    sh 'terraform plan -out plans/plan.tf > plans/plan.txt'                }
                }
        }
        stage('Terraform action') {
            steps {
                dir("cloud/terraform") {
                    sh "terraform ${action} -auto-approve"
                }
            } 
        }
    }
}