pipeline {

    agent any




    stages {

        stage('Terraform init') {
             dir("folder") {
                sh "terraform"

                steps {

                    sh 'terraform init'

                }
            }
        }

        stage('Terraform action') {
             dir("folder") {
               sh "terraform"
                    steps {

                        sh "terraform ${action} -auto-approve"

                    }
             }

        }



    }




}