pipeline {

    agent any

    stages {

        stage('Set up environment'){
            steps{
                script{
                    env.ENVIRONMENT="dev"
                    env.TF_VAR_environment="${ENVIRONMENT}"
                    env.TF_VAR_region="${region}"
                    env.TF_VAR_public_subnet_1="Jenkins-Public-1-c"
                    env.TF_VAR_public_subnet_2="Jenkins-Public-2"
                    env.TF_VAR_private_subnet_1="Jenkins-Private-3"
                    env.TF_VAR_private_subnet_2="Jenkins-Private-4"

                    env.TF_VAR_instance_type="db.t2.micro"
                    env.TF_VAR_ami_id="ami-00f7e5c52c0f43726"
                    env.TF_VAR_cluster_name="UtopiaClusterWC"
                }
            }
        }
        stage('Terraform init') {

            steps {
                dir("terraform/terraform_v3") {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform plan') {

            steps {
                dir("terraform/terraform_v3") {
                    sh 'terraform plan'                }
                }
        }
        stage('Terraform action') {
            steps {
                dir("terraform/terraform_v3") {
                    sh "terraform ${action} -auto-approve"
                }
            } 
        }
    }
}
