pipeline {

    agent any

    stages {

        stage('Set up environment'){
            steps{
                script{
                    env.ENVIRONMENT="dev"
                    env.region = "us-west-2"
                }
            }
        }
        stage('Terraform init') {

            steps {
                dir("terraform/terraform_v3") {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform plan') {

            steps {
                dir("terraform/terraform_v3") {
                    sh 'terraform plan'                }
                }
        }
        stage('Terraform action') {
            steps {
                dir("terraform/terraform_v3") {
                    sh "terraform ${action} -auto-approve"
                }
            } 
        }
    }
}
