pipeline {

    agent any

    stages {

        stage('Set up environment'){
            steps{
                script{
                    env.TF_VAR_environment="dev"
                    env.TF_VAR_region="${region}"
                    env.TF_VAR_public_subnet_1="Jenkins-Public-1-c"
                    env.TF_VAR_public_subnet_2="Jenkins-Public-2"
                    env.TF_VAR_private_subnet_1="Jenkins-Private-1"
                    env.TF_VAR_private_subnet_2="Jenkins-Private-2"

                    env.TF_VAR_users_repo="${USER_REPO_WC}"
                    env.TF_VAR_flights_repo="${FLIGHT_REPO_WC}"
                    env.TF_VAR_bookings_repo="${BOOKING_REPO_WC}"
                    env.TF_VAR_frontend_repo="${FRONTEND_REPO_WC}"
                }
            }
        }
        stage('Terraform init') {

            steps {
                dir("terraform/terraform_v3") {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform plan') {

            steps {
                dir("terraform/terraform_v3") {
                    sh 'terraform plan'                }
                }
        }
        stage('Terraform action') {
            steps {
                dir("terraform/terraform_v3") {
                    sh "terraform ${action} -auto-approve"
                }
            } 
        }
    }
}
