pipeline {

    agent any

    stages{
        stage('Setup parameters') {
            steps {
                    script {
                    properties([
                            parameters([
                                [$class: 'ChoiceParameter', 
                                    choiceType: 'PT_SINGLE_SELECT', 
                                    description: 'Select the action to perform', 
                                    filterLength: 1, 
                                    filterable: false, 
                                    name: 'action', 
                                    script: [
                                        $class: 'GroovyScript', 
                                        fallbackScript: [
                                            classpath: [], 
                                            sandbox: false, 
                                            script: 
                                                "return['Could not load actions']"
                                        ], 
                                        script: [
                                            classpath: [], 
                                            sandbox: false, 
                                            script: 
                                                "return['create','destroy']"
                                        ]
                                    ]
                                ],
                                [$class: 'ChoiceParameter', 
                                    choiceType: 'PT_SINGLE_SELECT', 
                                    description: 'Select the environment', 
                                    filterLength: 1, 
                                    filterable: false, 
                                    name: 'environment', 
                                    script: [
                                        $class: 'GroovyScript', 
                                        fallbackScript: [
                                            classpath: [], 
                                            sandbox: false, 
                                            script: 
                                                "return['Could not load environment']"
                                        ], 
                                        script: [
                                            classpath: [], 
                                            sandbox: false, 
                                            script: 
                                                "return['dev','prod']"
                                        ]
                                    ]
                                ]
                            ])
                        ])
                    }
                }
            }
            stage('Set up Environment Variables'){
                steps{
                    script {
                        env.ENVIRONMENT = params.environment
                        env.DB_HOST = sh ( script: 'aws secretsmanager get-secret-value --secret-id prod/Walter/secrets --region us-west-2  | jq --raw-output .SecretString | jq -r ."db_host"', returnStdout: true).trim()
                        env.SECRET_KEY = sh ( script: 'aws secretsmanager get-secret-value --secret-id prod/Walter/secrets --region us-west-2  | jq --raw-output .SecretString | jq -r ."secret_key"', returnStdout: true).trim()
                        env.DB_USER = sh ( script: 'aws secretsmanager get-secret-value --secret-id prod/Walter/secrets --region us-west-2  | jq --raw-output .SecretString | jq -r ."db_username"', returnStdout: true).trim()
                        env.DB_USER_PASSWORD = sh ( script: 'aws secretsmanager get-secret-value --secret-id prod/Walter/secrets --region us-west-2  | jq --raw-output .SecretString | jq -r ."db_password"', returnStdout: true).trim()                
                    }
                }
            }
            stage('Run Ansible Playbook') {
                steps {
                    ansibleTower(
                    towerServer: 'Tower 1',
                    jobTemplate: 'EKS',
                    jobTags: params.action,
                    verbose: true,
                    extraVars: '''---
                    ENVIRONMENT: "$ENVIRONMENT"
                    VPC_NAME: "Jenkins-VPC"
                    REGION: "us-west-2"
                    DB_HOST: "$DB_HOST"
                    SECRET_KEY: "$SECRET_KEY
                    DB_USER: "$DB_USER"
                    DB_USER_PASSWORD: "$DB_USER_PASSWORD"
                    CLUSTER_NAME: "$CLUSTER_NAME_WC"
                    AWS_ACCOUNT_ID: "$ORG_ACCOUNT_NUM"
                    RECORD_NAME: "wc-eks-utopia.hitwc.link"
                    HOSTED_ZONE: "$HOSTED_ZONE"
                    EKS_LOCATION: "../../kubernetes/eks"
                    USERS_NUM_POD: "1"
                    FLIGHTS_NUM_POD: "2"
                    BOOKINGS_NUM_POD: "2"
                    FRONTEND_NUM_POD: "2"
                    ''')
                }
            }
        }
}