pipeline {

    agent any

    stages {
        stage('Setup parameters') {
            steps {
                    script {
                    properties([
                                [$class: 'ChoiceParameter', 
                                    choiceType: 'PT_SINGLE_SELECT', 
                                    description: 'Select the action', 
                                    filterLength: 1, 
                                    filterable: false, 
                                    name: 'action', 
                                    script: [
                                        $class: 'GroovyScript', 
                                        fallbackScript: [
                                            classpath: [], 
                                            sandbox: false, 
                                            script: 
                                                "return['Could not load actions']"
                                        ], 
                                        script: [
                                            classpath: [], 
                                            sandbox: false, 
                                            script: 
                                                "return['apply','destroy']"
                                        ]
                                    ]
                                ]
                            ])
                        ])
                    }
                }
        }
        stage('Set up environment'){
            steps{
                script{
                    env.TF_VAR_environment="dev"
                    env.TF_VAR_region="${REGION_WC}"
                    env.TF_VAR_cluster_name="${CLUSTER_NAME_WC}"
                    env.TF_VAR_bastion_host_type="db.t2.micro"
                    env.TF_VAR_vpc_name="${WC_vpc_name}"
                    env.TF_VAR_peering_vpc_name = "Jenkins-VPC"
                    env.TF_VAR_aws_account_id = "${ORG_ACCOUNT_NUM}"

                    env.TF_VAR_ssm_path="${WC_SECRETS_PATH_DEV}"
                    env.TF_VAR_key_name="${SSH_GROUP_KEY}"
                }
            }
        }
        stage('Terraform init') {

            steps {
                dir("terraform/terraform_v2") {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform plan') {

            steps {
                dir("terraform/terraform_v2") {
                    sh 'terraform plan'                
                    }
            }
        }
        stage('Terraform action') {
            steps {
                dir("terraform/terraform_v2") {
                    sh "terraform ${action} -auto-approve"
                }
            } 
        }
    }
}
