pipeline {

    agent any

    stages {
        stage('Setup parameters') {
            steps {
                script {
                    properties([
                        parameters([
                            [$class: 'ChoiceParameter', 
                                choiceType: 'PT_SINGLE_SELECT', 
                                description: 'Select the action', 
                                filterLength: 1, 
                                filterable: false, 
                                name: 'action', 
                                script: [
                                    $class: 'GroovyScript', 
                                    fallbackScript: [
                                        classpath: [], 
                                        sandbox: false, 
                                        script: 
                                            "return['Could not load actions']"
                                    ], 
                                    script: [
                                        classpath: [], 
                                        sandbox: false, 
                                        script: 
                                            "return['apply','destroy']"
                                    ]
                                ]
                            ]
                        ])
                    ])
                }
            }
        }
        stage('Set up environment'){
            steps{
                script{
                    env.ENVIRONMENT                  ="dev"
                    env.TF_VAR_environment           ="dev"
                    env.TF_VAR_region                ="${REGION_WC}"
                    env.TF_VAR_cluster_name          ="${CLUSTER_NAME_WC}"
                    env.TF_VAR_vpc_name              ="${WC_vpc_name}"
                    env.TF_VAR_peering_vpc_name      = "${JENKINS_VPC}"
                    env.TF_VAR_aws_account_id        = "${ORG_ACCOUNT_NUM}"
                    env.TF_VAR_vpc_cidr_block        = "10.10.0.0/16"
                    env.TF_VAR_subnet1_cidr_block    = "10.10.1.0/24"
                    env.TF_VAR_subnet2_cidr_block    = "10.10.2.0/24"
                    env.TF_VAR_subnet3_cidr_block    = "10.10.3.0/24"
                    env.TF_VAR_subnet4_cidr_block    = "10.10.4.0/24"
                    env.TF_VAR_anywhere_ipv4         = "0.0.0.0/0"
                    env.TF_VAR_vpc_name              = "WC-vpc"
                    env.TF_VAR_pc_name               = "WC-Jenkins-pc"
                    env.TF_VAR_peering_rt_name       = "JenkinsRoutes"
                    env.TF_VAR_internet_gw_name      = "WC-ig"
                    env.TF_VAR_ssm_path              ="${WC_SECRETS_PATH_DEV}"
                    env.TF_VAR_key_name              ="${SSH_GROUP_KEY}"
                }
            }
        }
        stage('Terraform init') {

            steps {
                dir("terraform/networks") {
                    sh 'envsubst < config.tf > temp && rm config.tf && mv temp config.tf'
                    sh 'cat config.tf'
                    sh 'terraform init'
                }
            }
        }
        // stage('Terraform plan') {

        //     steps {
        //         script{
        //             dir("terraform/networks") {
        //                 if (params.action == 'destroy'){
        //                     sh 'terraform plan -destroy'             
        //                 }
        //                 else{
        //                     sh 'terraform plan'
        //                 }   
        //             }
        //         }
        //     }
        // }
        // stage('Terraform action') {
        //     steps {
        //         dir("terraform/networks") {
        //             sh "terraform ${action} -auto-approve"
        //         }
        //     } 
        // }
    }
}
