pipeline {

    agent any

    stages{
            stage('Set up Environment Variables'){
                steps{
                    script {
                        env.ENVIRONMENT = "dev"         
                    }
                }
            }
            stage('Run Ansible Playbook') {
                steps {
                    ansibleTower(
                    towerServer: 'Tower 1',
                    jobTemplate: 'EKS-delete-cluster',
                    verbose: true,
                    extraVars: '''---
                    ENVIRONMENT: "$ENVIRONMENT"
                    REGION: "us-west-2"
                    CLUSTER_NAME: "$CLUSTER_NAME_WC"
                    RECORD_NAME: "wc-eks-utopia.hitwc.link"
                    HOSTED_ZONE: "$HOSTED_ZONE"
                    ''')
                }
            }
        }
}