pipeline {
    agent any
    tools {
        go '1.18'
    }
    environment{
        ENVIRONMENT='testing'
        REGION="${REGION_WC}"
    }
    stages{
        stage('configure s3 backend'){
            steps{
                sh 'envsubst < config.tf > temp && rm config.tf && mv temp config.tf'
            }
        }
        stage('test'){
            steps{
                dir("terraform/networks/test") {
                    sh 'go version'
                    sh 'go mod tidy'
                    sh 'go test networks_test.go -v -timeout 10m'
                }
            }
            post{
                failure{
                    sh 'echo test failed'
                }
            }
        }
    }
}