pipeline {
    agent any 

    stages {
        stage('Setup parameters') {
            steps {
                script { 
                    properties([
                        parameters([
                            choice(
                                choices: ['dev', 'prod', 'test'], 
                                name: 'environment'
                            )
                        ])
                    ])
                }
            }
        }

        stage('setup environment'){
            steps{
                script{
                    env.AWS_DEFAULT_REGION  = "$REGION_WC"
                    env.VPC_ID              = sh (script: "aws ec2 describe-vpcs --filter Name=tag:Name,Values=${WC_vpc_name}-${params.environment} | jq '.[] | .[].VpcId'", returnStdout: true).trim().replaceAll("\"", "")
                    env.PRIVATE_SUBNET1     = sh( script: "aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} Name=tag:kubernetes.io/role/internal-elb,Values=1 --query Subnets[].SubnetId | jq '.[0]'", returnStdout: true).trim()
                    env.PRIVATE_SUBNET2     = sh( script: "aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} Name=tag:kubernetes.io/role/internal-elb,Values=1 --query Subnets[].SubnetId | jq '.[1]'", returnStdout: true).trim()
                    env.PUBLIC_SUBNET1      = sh( script: "aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} Name=tag:kubernetes.io/role/elb,Values=1 --query Subnets[].SubnetId | jq '.[0]'", returnStdout: true).trim()
                    env.PUBLIC_SUBNET2      = sh( script: "aws ec2 describe-subnets --filters Name=vpc-id,Values=${VPC_ID} Name=tag:kubernetes.io/role/elb,Values=1 --query Subnets[].SubnetId | jq '.[1]'", returnStdout: true).trim()
                }
            }
        } 
        stage('create'){
            steps{
                dir('ecs/cloudformation'){
                    sh "aws cloudformation deploy --stack-name ${CF_STACK_WC}-${params.environment} --template-file ./template.yaml --parameter-overrides \
                            ParameterKey=VpcId,ParameterValue=${VPC_ID} \
                            ParameterKey=LogGroupName,ParameterValue=${WC_ECS_LOGS} \
                            ParameterKey=PublicSubnet1,ParameterValue=${PUBLIC_SUBNET1} \
                            ParameterKey=PublicSubnet2,ParameterValue=${PUBLIC_SUBNET2} \
                            ParameterKey=PrivateSubnet1,ParameterValue=${PRIVATE_SUBNET1} \
                            ParameterKey=PrivateSubnet2,ParameterValue=${PRIVATE_SUBNET2} \
                            ParameterKey=AccountId,ParameterValue=${ORG_ACCOUNT_NUM} \
                            ParameterKey=HostedZoneId,ParameterValue=${HOSTED_ZONE} \
                            ParameterKey=RecordName,ParameterValue=${params.environment}-wc-ecs.${ROUTE53_DOMAIN} \
                            ParameterKey=ClusterName,ParameterValue=${CLUSTER_NAME_WC} \
                            ParameterKey=EnvType,ParameterValue=${params.environment} \
                            ParameterKey=ContainerPort,ParameterValue=${WC_CONTAINER_PORT} \
                            ParameterKey=Region,ParameterValue=${REGION_WC} \
                            ParameterKey=UsersRepo,ParameterValue=${USER_REPO_WC} \
                            ParameterKey=FlightsRepo,ParameterValue=${FLIGHT_REPO_WC} \
                            ParameterKey=BookingsRepo,ParameterValue=${BOOKING_REPO_WC} \
                            ParameterKey=FrontendRepo,ParameterValue=${FRONTEND_REPO_WC} \
                            ParameterKey=IamRole,ParameterValue=arn:aws:iam::${ORG_ACCOUNT_NUM}:role/ecsTaskExecutionRole \
                            ParameterKey=UsersFamily,ParameterValue=${USER_REPO_WC}-${params.environment}\
                            ParameterKey=FlightsFamily,ParameterValue=${FLIGHT_REPO_WC}-${params.environment} \
                            ParameterKey=BookingsFamily,ParameterValue=${BOOKING_REPO_WC}-${params.environment} \
                            ParameterKey=FrontendFamily,ParameterValue=${FRONTEND_REPO_WC}-${params.environment} \
                            ParameterKey=SSMSecretString,ParameterValue=${WC_SECRETS_PATH_DEV} \
                            ParameterKey=UsersHealthCheck,ParameterValue=${WC_HEALTH_USERS} \
                            ParameterKey=FlighstHealthCheck,ParameterValue=${WC_HEALTH_FLIGHTS} \
                            ParameterKey=BookingsHealthCheck,ParameterValue=${WC_HEALTH_BOOKINGS} \
                            ParameterKey=FrontendHealthCheck,ParameterValue=${WC_HEALTH_FRONTEND} \
                            ParameterKey=DbHost,ParameterValue=db_host \
                            ParameterKey=DbUser,ParameterValue=db_user \
                            ParameterKey=DbPassword,ParameterValue=db_password \
                            ParameterKey=SecretKey,ParameterValue=secret_key"
                }
            }
        }
        // stage('delete'){
        //     when {
        //         expression { 
        //            return params.action == 'delete'
        //         }
        //     }
        //     steps{
        //         withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'aws-key-WC', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY']]) {
        //             sh "aws cloudformation delete-stack --stack-name ${STACK_NAME}"               
        //         }
        //     }
        // }
    }
}