pipeline {
    // environment {
    //     USER_PORTS="5000"
    //     FLIGHT_PORTS="5001"
    //     BOOKING_PORTS="5002"
    // }

    agent any
    
    stages {
        stage('build'){
            steps {
                sh 'docker-compose -f docker-compose_local/docker-compose.yaml up -d'
            }
        }

    }

}