pipeline {
    environment {
        USER_PORT=5000
        FLIGHT_PORT=5001
        BOOKING_PORT=5002
    }

    agent any
    
    stages {
        stage('build'){
            steps {
                sh 'docker-compose -f jenkins_docker-compose/docker-compose.yaml up -d'
            }
        }

    }

}