---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: test
      shell: echo "hello world"

    - name: Switch Context to Cluster
      shell: |
        aws eks --region "{{ REGION }}" update-kubeconfig --name "{{ CLUSTER_NAME }}"

    - name: Rollout Restart Deployment
      shell: |
        kubectl rollout restart deployments/users-deployment