---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ./variables.yaml

  tasks:
  - name: find users ec2 instances
    ec2_instance_info:
      filters:
        "tag:Name": users_microservice
      region: "{{ region }}"
    register: ec2

  - name: debug for stuff
    debug: msg="{{ item.instance_id }}"
    loop: "{{ ec2.instances }}"