- name: Stop Microservice Instance
  hosts: localhost
  connection: local
  vars_files:
    - ../../../variables_team.yaml
  tasks:
  - name: Stop Users Instance
    ec2:
      instance_tags:
          Name: "{{ users_tag }}"
      state: stopped
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"

  - name: Stop Flights Instance
    ec2:
      instance_tags:
          Name: "{{ flights_tag }}"
      state: stopped
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"

  - name: Stop Bookings Instance
    ec2:
      instance_tags:
          Name: "{{ bookings_tag }}"
      state: stopped
      region: "{{ region }}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"