apiVersion: v1
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::026390315914:user/Jenkins 
      username: Jenkins 
      groups: 
      - system:masters
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::026390315914:role/eksctl-wc-cluster-FargatePodExecutionRole-CM5IX73TGTT5
      username: system:node:{{SessionName}}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  - system:node-proxier\n  rolearn: arn:aws:iam::026390315914:role/eksctl-wc-cluster-FargatePodExecutionRole-CM5IX73TGTT5\n  username: system:node:{{SessionName}}\n","mapUsers":"- userarn: arn:aws:iam::026390315914:user/Jenkins \n  username: Jenkins \n  groups: \n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-01-26T00:28:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "17033"
  uid: f5d6dd17-af98-4b87-9503-115f7f6626e1
