pipeline {
    agent any

    stages{
        
        stage('create cluster'){
            when {
                expression { 
                   return params.action == 'up'
                }
            }
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'aws-key-WC', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY']]) {

                    dir("cloud/kubernetes") {
                        sh 'chmod +x up.sh'
                        sh './up.sh'
                    }
                }
            }
        }
        stage('delete cluster'){
                    when {
                        expression { 
                        return params.action == 'down'
                        }
                    }
                    steps {
                        dir("cloud/kubernetes") {
                            sh './down.sh'
                        }
                    }
                }
    }



}