AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ContainerPort:
    Type: Number
    Default: 5000
  Image:
    Type: String
    Default: ""
  DbUserArn:
    Type: String
    Default: ""
  DbPasswordArn:
    Type: String
    Default: ""
  SecretKeyArn:
    Type: String
    Default: ""
  IamRole:
    Type: String
    Default: ""
  Family:
    Type: String
    Default: ""
  


Resources:
  UsersTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name: 
            Ref: ContainerPort
          Image: 
            Ref: Image
          Cpu: 10
          Memory: 512
          Environment: 
            - Name: USERS_PORT
              Value:
                Ref: ContainerPort
          PortMappings: 
            - ContainerPort:
                Ref: ContainerPort
              HostPort:
                Ref: ContainerPort
              Protocol: tcp
          Secrets: 
            - Name: DB_USER
              ValueFrom:
                Ref: DbUserArn
            - Name: DB_USER_PASSWORD
              ValueFrom:
                Ref: DbPasswordArn
            - Name: SECRET_KEY
              ValueFrom:
                Ref: SecretKeyArn
      Cpu: "1vCPU"
      ExecutionRoleArn:
        Ref: IamRole
      Family:
        Ref: Family
      Memory: "2GB"
      NetworkMode: "awsvpc"
      RequiresCompatibilities: 
        - "FARGATE"
      TaskRoleArn:
        Ref: IamRole