version: '3'
services:
  $SERVICE
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/${SERVICE}:latest"
    ports:
      - "${PORT}:${PORT}"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs_wc
        awslogs-region: ${REGION}
        awslogs-stream-prefix: ${SERVICE}