version: '3'
services:
  $SERVICE
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${SERVICE}:latest"
    ports:
      - "${PORT}:${PORT}"
    logging:
      driver: awslogs
      options:
        # Name: es
        # Host: "elk-docker-compose.hitwc.link"
        # Port: "5000"
        # Index: ${SERVICE}
        awslogs-group: "ecs_wc"
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ${SERVICE}
  # log_router:
  #   image: "docker.io/amazon/aws-for-fluent-bit:latest"
  #   logging:
  #     driver: awslogs
  #     options:
  #       awslogs-create-group: "true"
  #       awslogs-group: "ecs_wc"
  #       awslogs-region: ${AWS_REGION}
  #       awslogs-stream-prefix: ${SERVICE}
